namespace Softellect.AddressProcessor

/// Do not modify.
/// Generated by MD4_20191022.xlsx
type SuiteName =
    | Apt
    | Bldg

    // kk:20191024 - There are only 9 addresses with "FLOOR" suite name in MD4.
    // Unfortunately the abbreviation matches the state of FL.
    // Removing for the time being as it breaks everything FL related.
    // Keep the suite name here in case the things change.
    //| Fl

    | Frnt
    | Hngr
    | Lot
    | Num
    | Ofc
    | Ph
    | Rear
    | Rm
    | Side
    | Slip
    | Spc
    | Ste
    | Stop
    | Trlr
    | Unit

    static member all =
        [
            ( Apt, "APT", "APARTMENT" )
            ( Bldg, "BLDG", "BUILDING" )

            // kk:20191024 - There are only 9 addresses with "FLOOR" suite name in MD4.
            // Unfortunately the abbreviation matches the state of FL.
            // Removing for the time being as it breaks everything FL related.
            // Keep the suite name here in case the things change.
            //( Fl, "FL", "FLOOR" )

            ( Frnt, "FRNT", "FRONT" )
            ( Hngr, "HNGR", "HANGAR" )
            ( Lot, "LOT", "LOT" )
            ( Num, "#", "NUMBER" )
            ( Ofc, "OFC", "OFFICE" )
            ( Ph, "PH", "PENTHOUSE" )
            ( Rear, "REAR", "REAR" )
            ( Rm, "RM", "ROOM" )
            ( Side, "SIDE", "SIDE" )
            ( Slip, "SLIP", "SLIP" )
            ( Spc, "SPC", "SPACE" )
            ( Ste, "STE", "SUITE" )
            ( Stop, "STOP", "STOP" )
            ( Trlr, "TRLR", "TRAILER" )
            ( Unit, "UNIT", "UNIT" )
        ]

    static member allSuiteNames =
        (SuiteName.all |> List.map (fun (_, e, _) -> e))
        @
        (SuiteName.all |> List.map (fun (_, _, e) -> e))
        |> List.distinct
